proteingym_bm_file: assets/DMS_substitutions_Spearman_DMS_level.csv

model_names:
  - ProtSSN (ensemble)
  - SaProt (650M)
  - TranceptEVE L
  - VESPA
  - GEMME
  - ESM-IF1

ssemb_score_file_path: assets/df_total_proteingym_1.csv
